# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 21:29
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20160414_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
