# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20160415_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='recipients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='API.Account'),
        ),
    ]
