# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_feed_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='recipients',
        ),
        migrations.AddField(
            model_name='feed',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='inbox', to='API.Account'),
        ),
    ]
