# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=100, unique=True)),
                ('tuitionIS', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('tuitionOS', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('enrollGrad', models.IntegerField(null=True)),
                ('enrollUnder', models.IntegerField(null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('endowment', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('researchExp', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('datasource', models.CharField(default='Wikipedia', max_length=100, null=True)),
                ('ranking', models.IntegerField()),
            ],
        ),
    ]
